### ISSUE TITLE
Will a recursive function slow down the server if added to the service lifecycle.

### ISSUE THREAD

**Issue by L-van-der-merwe** [Nubuck/Z1-GANG-STARTER#10]
Hi,

I would like to know if you add this into your service lifecycle, what impact does it have on your overall performance of the application.

lifecycle: {
onSync(app) {
setTimeout(startFileProcessing, 15 * 60 * 1000, app)
},
},

currently what I am seeing is, every 15 minutes when the server uploads files from the local machine, the server is really slow in handling requests.

Is it a bad place to schedule that event?

The start file processing function is a recursive function that uploads all files that exists inside of a list from the local hard drive.

What can be added into the service lifecycle and what should we prevent adding into it? (What is the true purpose of the lifecycle)

**Comment by Nubuck** [comment]
Hey, yes if you aren't using a trampoline.

in @z1/preset-task there are both [sync](https://github.com/SaucecodeOfficial/zero-one-core/blob/master/presets/task/src/sync.js#L121) and [async](https://github.com/SaucecodeOfficial/zero-one-core/blob/master/presets/task/src/async.js#L30) trampoline functions.

Check this [article](https://blog.logrocket.com/using-trampolines-to-manage-large-recursive-loops-in-javascript-d8c9db095ae3/) for more details on trampolining.

Cheers
